add support for default values
mpollmeier/scalameta-serialiser pull request #3
Opened 2016-12-05 05:12 UTC by ariwaranosai

add support for default values by store default values map in companion object. 
Map needed to recombine to case class will be added to default map before get class params.

2016-12-05 05:25 UTC, ariwaranosai commented
if I was right, I also remove todo in README with this and change travis ci to test examples/test.

2016-12-05 23:23 UTC, mpollmeier requested changes
great stuff! see my comments and let me know your thoughts.

2016-12-05 23:23 UTC, mpollmeier commented on examples/src/test/scala/scala/meta/serialiser/MappableTest.scala
> +      WithDefaultValue.defaultValueMap shouldBe (Map[String, Any]("i" -> 13))
shouldn't this also contain `"s" -> "something"`?

2016-12-05 23:23 UTC, mpollmeier commented on README.md
>  ## current limitations (a.k.a. TODOs)
we could comment out the title here since this is empty atm

2016-12-05 23:23 UTC, mpollmeier commented on examples/src/test/scala/scala/meta/serialiser/MappableTest.scala
> +      WithDefaultValue.defaultValueMap shouldBe (Map[String, Any]("i" -> 13))
oh sorry, i misunderstood. can you delete the line above this (`val testInstance = WithDefaultValue(s = "something")`) to make this more obvious?

2016-12-05 23:23 UTC, mpollmeier commented on src/main/scala/scala/meta/serialiser/mappable.scala
> +      val defaultValue = paramss.flatten collect {
for readability's sake I'd suggest `val defaultValues: Seq[Term.ApplyInfix] = ...` here.. what do you think?

2016-12-06 04:00 UTC, ariwaranosai commented on README.md
>  ## current limitations (a.k.a. TODOs)
I find another limitations from comments. Maybe we can add `support for multiple constructor params lists` to this.

2016-12-06 04:02 UTC, ariwaranosai commented on src/main/scala/scala/meta/serialiser/mappable.scala
> +      val defaultValue = paramss.flatten collect {
good.

2016-12-06 04:07 UTC, ariwaranosai commented on src/main/scala/scala/meta/serialiser/mappable.scala
> +      val defaultValue = paramss.flatten collect {
good idea.

2016-12-06 13:36 UTC, ariwaranosai commented on examples/src/test/scala/scala/meta/serialiser/MappableTest.scala
> +      WithDefaultValue.defaultValueMap shouldBe (Map[String, Any]("i" -> 13))
I forget to delete it :-O

2016-12-06 18:05 UTC, merged